# Build settings
markdown: kramdown
theme: minima
header_files:
  - about.md
  - contact.md
# All pages.
{%- assign default_paths = site.pages | map: "path" -%}

# Use configured value if set, otherwise use all pages.
{%- assign page_paths = site.header_pages | default: default_paths -%}
